language: python
python:
  - "3.6"
install:
  - pip install tox coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - tox
after_success:
  - coveralls
